/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_device_OpenSLESSystem */

#ifndef _Included_org_jitsi_impl_neomedia_device_OpenSLESSystem
#define _Included_org_jitsi_impl_neomedia_device_OpenSLESSystem
#ifdef __cplusplus
extern "C" {
#endif
#undef org_jitsi_impl_neomedia_device_OpenSLESSystem_SL_DEFAULTDEVICEID_AUDIOINPUT
#define org_jitsi_impl_neomedia_device_OpenSLESSystem_SL_DEFAULTDEVICEID_AUDIOINPUT 4294967295i64
/*
 * Class:     org_jitsi_impl_neomedia_device_OpenSLESSystem
 * Method:    queryAudioInputCapabilities
 * Signature: (J[D[I[I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_jitsi_impl_neomedia_device_OpenSLESSystem_queryAudioInputCapabilities
  (JNIEnv *, jclass, jlong, jdoubleArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
