/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer */

#ifndef _Included_org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer
#define _Included_org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer
 * Method:    open
 * Signature: (Ljava/lang/String;DIIIILjava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer_open
  (JNIEnv *, jclass, jstring, jdouble, jint, jint, jint, jint, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer
 * Method:    process
 * Signature: (JLjava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer_process
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer_start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_renderer_audio_OpenSLESRenderer_stop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
