/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource */

#ifndef _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource
#define _Included_org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource
 * Method:    connect
 * Signature: (Ljava/lang/String;DIIIILjava/lang/Class;)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource_connect
  (JNIEnv *, jclass, jstring, jdouble, jint, jint, jint, jint, jclass);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource
 * Method:    disconnect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource_disconnect
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource
 * Method:    read
 * Signature: (JLjava/lang/Object;II)I
 */
JNIEXPORT jint JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource_read
  (JNIEnv *, jclass, jlong, jobject, jint, jint);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource_start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_jmfext_media_protocol_opensles_DataSource_stop
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
