/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jitsi_impl_neomedia_codec_video_h264_OMXDecoder */

#ifndef _Included_org_jitsi_impl_neomedia_codec_video_h264_OMXDecoder
#define _Included_org_jitsi_impl_neomedia_codec_video_h264_OMXDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jitsi_impl_neomedia_codec_video_h264_OMXDecoder
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_jitsi_impl_neomedia_codec_video_h264_OMXDecoder_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jitsi_impl_neomedia_codec_video_h264_OMXDecoder
 * Method:    open
 * Signature: (Ljava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_org_jitsi_impl_neomedia_codec_video_h264_OMXDecoder_open
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
